// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.
//
// For more information, visit https://firebase.google.com/docs/build
export const firebaseConfig = {
  "apiKey": "your-api-key",
  "authDomain": "your-auth-domain",
  "projectId": "your-project-id",
  "storageBucket": "your-storage-bucket",
  "messagingSenderId": "your-messaging-sender-id",
  "appId": "your-app-id"
};
